(setq perldoc-obarray (make-vector 1519 nil))
;; Functions
(mapc (lambda (func)
         (set (intern func perldoc-obarray) t))
'(
"*" "-A" "-B" "-C" "-M" "-O" "-R" "-S" "-T" "-W" "-X" "-b" "-c" "-d" "-e"
"-f" "-g" "-k" "-l" "-o" "-p" "-r" "-s" "-t" "-u" "-w" "-x" "-z"
"Otherwise," "Otherwise:" "abs" "accept" "alarm" "atan2" "bind" "binmode"
"bless" "break" "caller" "chdir" "chmod" "chomp" "chop" "chown" "chr"
"chroot" "close" "closedir" "connect" "continue" "cos" "crypt" "dbmclose"
"dbmopen" "default" "defined" "delete" "die" "do" "dump" "each" "endgrent"
"endhostent" "endnetent" "endprotoent" "endpwent" "endservent" "eof" "eval"
"exec" "exists" "exit" "exp" "fcntl" "fileno" "flock" "fork" "format"
"formline" "getc" "getgrent" "getgrgid" "getgrnam" "gethostbyaddr"
"gethostbyname" "gethostent" "getlogin" "getnetbyaddr" "getnetbyname"
"getnetent" "getpeername" "getpgrp" "getppid" "getpriority"
"getprotobyname" "getprotobynumber" "getprotoent" "getpwent" "getpwnam"
"getpwuid" "getservbyname" "getservbyport" "getservent" "getsockname"
"getsockopt" "given" "glob" "gmtime" "goto" "grep" "hex" "import" "index"
"int" "ioctl" "join" "keys" "kill" "last" "lc" "lcfirst" "length" "link"
"listen" "local" "localtime" "lock" "log" "lstat" "m" "map" "mkdir"
"msgctl" "msgget" "msgrcv" "msgsnd" "my" "next" "no" "oct" "open" "opendir"
"ord" "our" "pack" "package" "pipe" "pop" "pos" "print" "printf"
"prototype" "push" "q" "qq" "qr" "quotemeta" "qw" "qx" "rand" "read"
"readdir" "readline" "readlink" "readpipe" "recv" "redo" "ref" "rename"
"require" "reset" "return" "reverse" "rewinddir" "rindex" "rmdir" "s" "say"
"scalar" "seek" "seekdir" "select" "semctl" "semget" "semop" "send"
"setgrent" "sethostent" "setnetent" "setpgrp" "setpriority" "setprotoent"
"setpwent" "setservent" "setsockopt" "shift" "shmctl" "shmget" "shmread"
"shmwrite" "shutdown" "sin" "sleep" "socket" "socketpair" "sort" "splice"
"split" "sprintf" "sqrt" "srand" "stat" "state" "study" "sub" "substr"
"symlink" "syscall" "sysopen" "sysread" "sysseek" "system" "syswrite"
"tell" "telldir" "tie" "tied" "time" "times" "tr" "truncate" "uc" "ucfirst"
"umask" "undef" "unlink" "unpack" "unshift" "untie" "use" "utime" "values"
"vec" "wait" "waitpid" "wantarray" "warn" "when" "write" "y"))

;; Modules
(mapc (lambda (mod)
         (intern mod perldoc-obarray))
'(
"Algorithm::Diff" "Algorithm::DiffOld" "Alien::Tidyp"
"Alien::Tidyp::ConfigData" "AnyDBM_File" "Apache::SOAP"
"Apache::XMLRPC::Lite" "App::Cpan" "App::Prove" "App::Prove::State"
"App::Prove::State::Result" "App::Prove::State::Result::Test"
"App::local::lib::Win32Helper" "Archive::Extract" "Archive::Tar"
"Archive::Tar::Constant" "Archive::Tar::File" "Archive::Zip"
"Archive::Zip::Archive" "Archive::Zip::BufferedFileHandle"
"Archive::Zip::DirectoryMember" "Archive::Zip::FAQ"
"Archive::Zip::FileMember" "Archive::Zip::Member"
"Archive::Zip::MemberRead" "Archive::Zip::MockFileHandle"
"Archive::Zip::NewFileMember" "Archive::Zip::StringMember"
"Archive::Zip::Tree" "Archive::Zip::ZipFileMember" "Attribute::Handlers"
"AutoLoader" "AutoSplit" "B" "B::Concise" "B::Debug" "B::Deparse" "B::Lint"
"B::Lint::Debug" "B::Showlex" "B::Terse" "B::Xref" "Benchmark" "BerkeleyDB"
"BerkeleyDB::Btree" "BerkeleyDB::Hash" "Bundle::DBD::Pg"
"Bundle::DBD::mysql" "Bundle::DBI" "CGI" "CGI::Apache" "CGI::Carp"
"CGI::Cookie" "CGI::Fast" "CGI::Pretty" "CGI::Push" "CGI::Switch"
"CGI::Util" "CORE" "CPAN" "CPAN::API::HOWTO" "CPAN::Admin" "CPAN::Author"
"CPAN::Bundle" "CPAN::CacheMgr" "CPAN::Checksums" "CPAN::Complete"
"CPAN::Config" "CPAN::Debug" "CPAN::DeferredCode" "CPAN::DistnameInfo"
"CPAN::Distribution" "CPAN::Distroprefs" "CPAN::Distrostatus"
"CPAN::Exception::RecursiveDependency" "CPAN::Exception::blocked_urllist"
"CPAN::Exception::yaml_not_installed" "CPAN::Exception::yaml_process_error"
"CPAN::FTP" "CPAN::FTP::netrc" "CPAN::FirstTime" "CPAN::HTTP::Client"
"CPAN::HTTP::Credentials" "CPAN::HandleConfig" "CPAN::Index"
"CPAN::InfoObj" "CPAN::Inject" "CPAN::Kwalify" "CPAN::LWP::UserAgent"
"CPAN::Meta" "CPAN::Meta::Converter" "CPAN::Meta::Feature"
"CPAN::Meta::History" "CPAN::Meta::Prereqs" "CPAN::Meta::Spec"
"CPAN::Meta::Validator" "CPAN::Meta::YAML" "CPAN::Mirrors" "CPAN::Module"
"CPAN::Nox" "CPAN::Prompt" "CPAN::Queue" "CPAN::SQLite" "CPAN::SQLite::DBI"
"CPAN::SQLite::DBI::Index" "CPAN::SQLite::DBI::Search"
"CPAN::SQLite::Index" "CPAN::SQLite::Info" "CPAN::SQLite::META"
"CPAN::SQLite::Populate" "CPAN::SQLite::Search" "CPAN::SQLite::State"
"CPAN::SQLite::Util" "CPAN::Shell" "CPAN::Tarzip" "CPAN::URL"
"CPAN::Version" "CPANPLUS" "CPANPLUS::Backend" "CPANPLUS::Backend::RV"
"CPANPLUS::Config" "CPANPLUS::Configure" "CPANPLUS::Configure::Setup"
"CPANPLUS::Dist" "CPANPLUS::Dist::Autobundle" "CPANPLUS::Dist::Base"
"CPANPLUS::Dist::Build" "CPANPLUS::Dist::Build::Constants"
"CPANPLUS::Dist::MM" "CPANPLUS::Dist::Sample" "CPANPLUS::Error"
"CPANPLUS::FAQ" "CPANPLUS::Hacking" "CPANPLUS::Internals"
"CPANPLUS::Internals::Constants" "CPANPLUS::Internals::Constants::Report"
"CPANPLUS::Internals::Extract" "CPANPLUS::Internals::Fetch"
"CPANPLUS::Internals::Report" "CPANPLUS::Internals::Search"
"CPANPLUS::Internals::Source" "CPANPLUS::Internals::Source::Memory"
"CPANPLUS::Internals::Source::SQLite"
"CPANPLUS::Internals::Source::SQLite::Tie" "CPANPLUS::Internals::Utils"
"CPANPLUS::Internals::Utils::Autoflush" "CPANPLUS::Module"
"CPANPLUS::Module::Author" "CPANPLUS::Module::Author::Fake"
"CPANPLUS::Module::Checksums" "CPANPLUS::Module::Fake"
"CPANPLUS::Module::Signature" "CPANPLUS::Selfupdate" "CPANPLUS::Shell"
"CPANPLUS::Shell::Classic" "CPANPLUS::Shell::Default"
"CPANPLUS::Shell::Default::Plugins::CustomSource"
"CPANPLUS::Shell::Default::Plugins::HOWTO"
"CPANPLUS::Shell::Default::Plugins::Remote"
"CPANPLUS::Shell::Default::Plugins::Source" "Capture::Tiny" "Carp"
"Carp::Heavy" "Catalyst" "Catalyst::Action" "Catalyst::ActionContainer"
"Catalyst::AttrContainer" "Catalyst::Base" "Catalyst::Build"
"Catalyst::Component" "Catalyst::Controller" "Catalyst::Controller::CRUD"
"Catalyst::Controller::CRUD::CDBI" "Catalyst::Controller::CRUD::DBIC"
"Catalyst::DispatchType" "Catalyst::DispatchType::Default"
"Catalyst::DispatchType::Index" "Catalyst::DispatchType::Path"
"Catalyst::DispatchType::Regex" "Catalyst::Dispatcher" "Catalyst::Engine"
"Catalyst::Engine::Apache" "Catalyst::Engine::Apache2"
"Catalyst::Engine::Apache2::MP19" "Catalyst::Engine::Apache2::MP20"
"Catalyst::Engine::Apache::MP13" "Catalyst::Engine::CGI"
"Catalyst::Engine::FastCGI" "Catalyst::Engine::HTTP"
"Catalyst::Engine::HTTP::Restarter"
"Catalyst::Engine::HTTP::Restarter::Watcher" "Catalyst::Exception"
"Catalyst::Helper" "Catalyst::Helper::Lighttpd" "Catalyst::Helper::Lighty"
"Catalyst::Helper::Model::Adaptor" "Catalyst::Helper::Model::CRUD"
"Catalyst::Helper::Model::DBIC::Schema" "Catalyst::Helper::Model::Factory"
"Catalyst::Helper::Model::Factory::PerRequest"
"Catalyst::Helper::Prototype" "Catalyst::Helper::View::TT"
"Catalyst::Helper::View::TTSite" "Catalyst::Log" "Catalyst::Log::Log4perl"
"Catalyst::Manual" "Catalyst::Manual::About" "Catalyst::Manual::Cookbook"
"Catalyst::Manual::FAQ" "Catalyst::Manual::Internals"
"Catalyst::Manual::Intro" "Catalyst::Manual::Plugins"
"Catalyst::Manual::Tutorial" "Catalyst::Manual::WritingPlugins"
"Catalyst::Model" "Catalyst::Model::Adaptor"
"Catalyst::Model::Adaptor::Base" "Catalyst::Model::DBIC::Schema"
"Catalyst::Model::Factory" "Catalyst::Model::Factory::PerRequest"
"Catalyst::Plugin::Authentication"
"Catalyst::Plugin::Authentication::Credential::Password"
"Catalyst::Plugin::Authentication::Internals"
"Catalyst::Plugin::Authentication::Store"
"Catalyst::Plugin::Authentication::Store::DBIC"
"Catalyst::Plugin::Authentication::Store::DBIC::Backend"
"Catalyst::Plugin::Authentication::Store::DBIC::User"
"Catalyst::Plugin::Authentication::Store::DBIC::User::CDBI"
"Catalyst::Plugin::Authentication::Store::DBIx::Class"
"Catalyst::Plugin::Authentication::Store::DBIx::Class::User"
"Catalyst::Plugin::Authentication::Store::Htpasswd"
"Catalyst::Plugin::Authentication::Store::Htpasswd::Backend"
"Catalyst::Plugin::Authentication::Store::Htpasswd::User"
"Catalyst::Plugin::Authentication::Store::Minimal"
"Catalyst::Plugin::Authentication::User"
"Catalyst::Plugin::Authentication::User::Hash"
"Catalyst::Plugin::Authorization::ACL"
"Catalyst::Plugin::Authorization::ACL::Engine"
"Catalyst::Plugin::Authorization::Roles" "Catalyst::Plugin::CRUD"
"Catalyst::Plugin::Cache::FastMmap" "Catalyst::Plugin::Cache::Memcached"
"Catalyst::Plugin::Charsets::Japanese"
"Catalyst::Plugin::Charsets::Japanese::Nihongo"
"Catalyst::Plugin::CodeEval" "Catalyst::Plugin::Compress::Deflate"
"Catalyst::Plugin::Compress::Gzip" "Catalyst::Plugin::Compress::Zlib"
"Catalyst::Plugin::ConfigLoader" "Catalyst::Plugin::ConfigLoader::YAML"
"Catalyst::Plugin::Crypt::CBC" "Catalyst::Plugin::DefaultEnd"
"Catalyst::Plugin::Email" "Catalyst::Plugin::HTML::Widget"
"Catalyst::Plugin::I18N" "Catalyst::Plugin::JSONRPC"
"Catalyst::Plugin::Log::Dispatch" "Catalyst::Plugin::Pluggable"
"Catalyst::Plugin::Prototype" "Catalyst::Plugin::Redirect"
"Catalyst::Plugin::Session" "Catalyst::Plugin::Session::State"
"Catalyst::Plugin::Session::State::Cookie"
"Catalyst::Plugin::Session::State::URI" "Catalyst::Plugin::Session::Store"
"Catalyst::Plugin::Session::Store::CDBI"
"Catalyst::Plugin::Session::Store::DBIC"
"Catalyst::Plugin::Session::Store::Dummy"
"Catalyst::Plugin::Session::Store::FastMmap"
"Catalyst::Plugin::Session::Store::File"
"Catalyst::Plugin::Session::Store::Memcached"
"Catalyst::Plugin::Session::Test::Store"
"Catalyst::Plugin::Session::Tutorial" "Catalyst::Plugin::Singleton"
"Catalyst::Plugin::StackTrace" "Catalyst::Plugin::Static::Simple"
"Catalyst::Plugin::SubRequest" "Catalyst::Plugin::UploadProgress"
"Catalyst::Plugin::UploadProgress::Static" "Catalyst::Plugin::XMLRPC"
"Catalyst::Plugin::XMLRPC::DispatchType::XMLRPC" "Catalyst::Request"
"Catalyst::Request::Upload" "Catalyst::Response" "Catalyst::Test"
"Catalyst::Utils" "Catalyst::View" "Catalyst::View::GD::Barcode"
"Catalyst::View::SVGTTGraph" "Catalyst::View::TT" "Class::ErrorHandler"
"Class::Inspector" "Class::Inspector::Functions" "Class::Loader"
"Class::LoaderTest" "Class::Struct" "Compress::Bzip2"
"Compress::Raw::Bzip2" "Compress::Raw::Lzma" "Compress::Raw::Zlib"
"Compress::Zlib" "Compress::unLZMA" "Config" "Config::Extensions"
"Convert::ASCII::Armor" "Convert::ASCII::Armour" "Convert::ASN1"
"Convert::ASN1::Debug" "Convert::ASN1::IO" "Convert::ASN1::_decode"
"Convert::ASN1::_encode" "Convert::ASN1::parser" "Convert::PEM"
"Convert::PEM::CBC" "Crypt::Blowfish" "Crypt::CAST5_PP"
"Crypt::CAST5_PP::Tables" "Crypt::CBC" "Crypt::DES" "Crypt::DES_EDE3"
"Crypt::DH" "Crypt::DSA" "Crypt::DSA::Key" "Crypt::DSA::Key::PEM"
"Crypt::DSA::Key::SSH2" "Crypt::DSA::KeyChain" "Crypt::DSA::Signature"
"Crypt::DSA::Util" "Crypt::IDEA" "Crypt::OpenPGP" "Crypt::OpenPGP::Armour"
"Crypt::OpenPGP::Buffer" "Crypt::OpenPGP::CFB"
"Crypt::OpenPGP::Certificate" "Crypt::OpenPGP::Cipher"
"Crypt::OpenPGP::Ciphertext" "Crypt::OpenPGP::Compressed"
"Crypt::OpenPGP::Config" "Crypt::OpenPGP::Constants"
"Crypt::OpenPGP::Digest" "Crypt::OpenPGP::ErrorHandler"
"Crypt::OpenPGP::Key" "Crypt::OpenPGP::Key::Public"
"Crypt::OpenPGP::Key::Public::DSA" "Crypt::OpenPGP::Key::Public::ElGamal"
"Crypt::OpenPGP::Key::Public::RSA" "Crypt::OpenPGP::Key::Secret"
"Crypt::OpenPGP::Key::Secret::DSA" "Crypt::OpenPGP::Key::Secret::ElGamal"
"Crypt::OpenPGP::Key::Secret::RSA" "Crypt::OpenPGP::KeyBlock"
"Crypt::OpenPGP::KeyRing" "Crypt::OpenPGP::KeyServer" "Crypt::OpenPGP::MDC"
"Crypt::OpenPGP::Marker" "Crypt::OpenPGP::Message"
"Crypt::OpenPGP::OnePassSig" "Crypt::OpenPGP::PacketFactory"
"Crypt::OpenPGP::Plaintext" "Crypt::OpenPGP::S2k"
"Crypt::OpenPGP::SKSessionKey" "Crypt::OpenPGP::SessionKey"
"Crypt::OpenPGP::Signature" "Crypt::OpenPGP::Signature::SubPacket"
"Crypt::OpenPGP::Trust" "Crypt::OpenPGP::UserID" "Crypt::OpenPGP::Util"
"Crypt::OpenPGP::Words" "Crypt::Primes" "Crypt::RIPEMD160"
"Crypt::RIPEMD160::MAC" "Crypt::RSA" "Crypt::RSA::DataFormat"
"Crypt::RSA::Debug" "Crypt::RSA::ES::OAEP" "Crypt::RSA::ES::PKCS1v15"
"Crypt::RSA::Errorhandler" "Crypt::RSA::Key" "Crypt::RSA::Key::Private"
"Crypt::RSA::Key::Private::SSH" "Crypt::RSA::Key::Public"
"Crypt::RSA::Key::Public::SSH" "Crypt::RSA::Primitives"
"Crypt::RSA::SS::PKCS1v15" "Crypt::RSA::SS::PSS" "Crypt::Random"
"Crypt::Random::Generator" "Crypt::Random::Provider::File"
"Crypt::Random::Provider::devrandom" "Crypt::Random::Provider::devurandom"
"Crypt::Random::Provider::egd" "Crypt::Random::Provider::rand"
"Crypt::Rijndael" "Crypt::SSLeay" "Crypt::SSLeay::CTX"
"Crypt::SSLeay::Conn" "Crypt::SSLeay::Err" "Crypt::SSLeay::MainContext"
"Crypt::SSLeay::X509" "Crypt::Twofish" "Cwd" "DB" "DBD::ADO"
"DBD::ADO::Const" "DBD::ADO::GetInfo" "DBD::ADO::TypeInfo" "DBD::DBM"
"DBD::ExampleP" "DBD::File" "DBD::File::Developers" "DBD::File::HowTo"
"DBD::File::Roadmap" "DBD::Gofer" "DBD::Gofer::Policy::Base"
"DBD::Gofer::Policy::classic" "DBD::Gofer::Policy::pedantic"
"DBD::Gofer::Policy::rush" "DBD::Gofer::Transport::Base"
"DBD::Gofer::Transport::corostream" "DBD::Gofer::Transport::null"
"DBD::Gofer::Transport::pipeone" "DBD::Gofer::Transport::stream"
"DBD::NullP" "DBD::ODBC" "DBD::ODBC::Changes" "DBD::ODBC::FAQ"
"DBD::ODBC::TO_DO" "DBD::Pg" "DBD::Proxy" "DBD::SQLite"
"DBD::SQLite::Cookbook" "DBD::Sponge" "DBD::mysql" "DBD::mysql::GetInfo"
"DBD::mysql::INSTALL" "DBI" "DBI::Changes" "DBI::Const::GetInfo::ANSI"
"DBI::Const::GetInfo::ODBC" "DBI::Const::GetInfoReturn"
"DBI::Const::GetInfoType" "DBI::DBD" "DBI::DBD::Metadata"
"DBI::DBD::SqlEngine" "DBI::DBD::SqlEngine::Developers"
"DBI::DBD::SqlEngine::HowTo" "DBI::FAQ" "DBI::Gofer::Execute"
"DBI::Gofer::Request" "DBI::Gofer::Response" "DBI::Gofer::Serializer::Base"
"DBI::Gofer::Serializer::DataDumper" "DBI::Gofer::Serializer::Storable"
"DBI::Gofer::Transport::Base" "DBI::Gofer::Transport::pipeone"
"DBI::Gofer::Transport::stream" "DBI::Profile" "DBI::ProfileData"
"DBI::ProfileDumper" "DBI::ProfileDumper::Apache" "DBI::ProfileSubs"
"DBI::ProxyServer" "DBI::PurePerl" "DBI::SQL::Nano"
"DBI::Util::CacheMemory" "DBI::Util::_accessor" "DBI::W32ODBC"
"DBIx::Simple" "DBIx::Simple::Comparison" "DBIx::Simple::Examples"
"DBIx::Simple::Result::RowObject" "DBM::Deep" "DBM::Deep::Array"
"DBM::Deep::ConfigData" "DBM::Deep::Cookbook" "DBM::Deep::Engine"
"DBM::Deep::Engine::DBI" "DBM::Deep::Engine::File" "DBM::Deep::Hash"
"DBM::Deep::Internals" "DBM::Deep::Iterator" "DBM::Deep::Iterator::DBI"
"DBM::Deep::Iterator::File" "DBM::Deep::Iterator::File::BucketList"
"DBM::Deep::Iterator::File::Index" "DBM::Deep::Null" "DBM::Deep::Sector"
"DBM::Deep::Sector::DBI" "DBM::Deep::Sector::DBI::Reference"
"DBM::Deep::Sector::DBI::Scalar" "DBM::Deep::Sector::File"
"DBM::Deep::Sector::File::BucketList" "DBM::Deep::Sector::File::Data"
"DBM::Deep::Sector::File::Index" "DBM::Deep::Sector::File::Null"
"DBM::Deep::Sector::File::Reference" "DBM::Deep::Sector::File::Scalar"
"DBM::Deep::Storage" "DBM::Deep::Storage::DBI" "DBM::Deep::Storage::File"
"DBM_Filter" "DBM_Filter::compress" "DBM_Filter::encode"
"DBM_Filter::int32" "DBM_Filter::null" "DBM_Filter::utf8" "DB_File"
"Data::Buffer" "Data::Compare" "Data::Compare::Plugins"
"Data::Compare::Plugins::Scalar::Properties" "Data::Dumper" "Data::Random"
"Data::Random::WordList" "Devel::DProf" "Devel::DProf::V"
"Devel::InnerPackage" "Devel::PPPort" "Devel::Peek" "Devel::SelfStubber"
"Digest" "Digest::BubbleBabble" "Digest::HMAC" "Digest::HMAC_MD5"
"Digest::HMAC_SHA1" "Digest::MD2" "Digest::MD5" "Digest::SHA"
"Digest::SHA1" "Digest::base" "Digest::file" "DirHandle" "Dumpvalue"
"DynaLoader" "Emacs::PDE" "Emacs::PDE::Util" "Encode" "Encode::Alias"
"Encode::Byte" "Encode::CJKConstants" "Encode::CN" "Encode::CN::HZ"
"Encode::Config" "Encode::EBCDIC" "Encode::Encoder" "Encode::Encoding"
"Encode::GSM0338" "Encode::Guess" "Encode::JP" "Encode::JP::H2Z"
"Encode::JP::JIS7" "Encode::KR" "Encode::KR::2022_KR" "Encode::Locale"
"Encode::MIME::Header" "Encode::MIME::Header::ISO_2022_JP"
"Encode::MIME::Name" "Encode::PerlIO" "Encode::Supported" "Encode::Symbol"
"Encode::TW" "Encode::Unicode" "Encode::Unicode::UTF7" "English" "Env"
"Errno" "Exporter" "Exporter::Heavy" "ExtUtils::CBuilder"
"ExtUtils::CBuilder::Base" "ExtUtils::CBuilder::Platform::Unix"
"ExtUtils::CBuilder::Platform::VMS" "ExtUtils::CBuilder::Platform::Windows"
"ExtUtils::CBuilder::Platform::Windows::BCC"
"ExtUtils::CBuilder::Platform::Windows::GCC"
"ExtUtils::CBuilder::Platform::Windows::MSVC"
"ExtUtils::CBuilder::Platform::aix" "ExtUtils::CBuilder::Platform::cygwin"
"ExtUtils::CBuilder::Platform::darwin"
"ExtUtils::CBuilder::Platform::dec_osf" "ExtUtils::CBuilder::Platform::os2"
"ExtUtils::Command" "ExtUtils::Command::MM" "ExtUtils::Constant"
"ExtUtils::Constant::Base" "ExtUtils::Constant::ProxySubs"
"ExtUtils::Constant::Utils" "ExtUtils::Constant::XS" "ExtUtils::Embed"
"ExtUtils::Install" "ExtUtils::Installed" "ExtUtils::Liblist"
"ExtUtils::Liblist::Kid" "ExtUtils::MM" "ExtUtils::MM_AIX"
"ExtUtils::MM_Any" "ExtUtils::MM_BeOS" "ExtUtils::MM_Cygwin"
"ExtUtils::MM_DOS" "ExtUtils::MM_Darwin" "ExtUtils::MM_MacOS"
"ExtUtils::MM_NW5" "ExtUtils::MM_OS2" "ExtUtils::MM_QNX"
"ExtUtils::MM_UWIN" "ExtUtils::MM_Unix" "ExtUtils::MM_VMS"
"ExtUtils::MM_VOS" "ExtUtils::MM_Win32" "ExtUtils::MM_Win95" "ExtUtils::MY"
"ExtUtils::MakeMaker" "ExtUtils::MakeMaker::Config"
"ExtUtils::MakeMaker::FAQ" "ExtUtils::MakeMaker::Tutorial"
"ExtUtils::MakeMaker::YAML" "ExtUtils::Manifest" "ExtUtils::Miniperl"
"ExtUtils::Mkbootstrap" "ExtUtils::Mksymlists" "ExtUtils::Packlist"
"ExtUtils::ParseXS" "ExtUtils::ParseXS::Constants"
"ExtUtils::ParseXS::CountLines" "ExtUtils::ParseXS::Utilities"
"ExtUtils::Typemaps" "ExtUtils::Typemaps::InputMap"
"ExtUtils::Typemaps::OutputMap" "ExtUtils::Typemaps::Type"
"ExtUtils::testlib" "FCGI" "Fatal" "Fcntl" "File::Basename"
"File::CheckTree" "File::Compare" "File::Copy" "File::Copy::Recursive"
"File::DosGlob" "File::Fetch" "File::Find" "File::Find::Rule"
"File::Find::Rule::Extending" "File::Find::Rule::Procedural" "File::Glob"
"File::GlobMapper" "File::HomeDir" "File::HomeDir::Darwin"
"File::HomeDir::Darwin::Carbon" "File::HomeDir::Darwin::Cocoa"
"File::HomeDir::Driver" "File::HomeDir::FreeDesktop"
"File::HomeDir::MacOS9" "File::HomeDir::Test" "File::HomeDir::Unix"
"File::HomeDir::Windows" "File::Listing" "File::Path" "File::Remove"
"File::ShareDir" "File::Slurp" "File::Spec" "File::Spec::Cygwin"
"File::Spec::Epoc" "File::Spec::Functions" "File::Spec::Mac"
"File::Spec::OS2" "File::Spec::Unix" "File::Spec::VMS" "File::Spec::Win32"
"File::Temp" "File::Which" "File::chmod" "File::pushd" "File::stat"
"FileCache" "FileHandle" "Filter::Simple" "Filter::Util::Call"
"Filter::Util::Exec" "Filter::cpp" "Filter::decrypt" "Filter::exec"
"Filter::sh" "Filter::tee" "FindBin" "GD" "GD::Group" "GD::Image"
"GD::Polygon" "GD::Polyline" "GD::Simple" "GDBM_File" "Getopt::Long"
"Getopt::Std" "HTML::Entities" "HTML::Filter" "HTML::HeadParser"
"HTML::LinkExtor" "HTML::Parser" "HTML::PullParser" "HTML::Tagset"
"HTML::TokeParser" "HTTP::Config" "HTTP::Cookies"
"HTTP::Cookies::Microsoft" "HTTP::Cookies::Netscape" "HTTP::Daemon"
"HTTP::Date" "HTTP::Headers" "HTTP::Headers::Auth" "HTTP::Headers::ETag"
"HTTP::Headers::Util" "HTTP::Message" "HTTP::Negotiate" "HTTP::Request"
"HTTP::Request::Common" "HTTP::Response" "HTTP::Status" "HTTP::Tiny"
"Hash::Util" "Hash::Util::FieldHash" "I18N::Collate" "I18N::LangTags"
"I18N::LangTags::Detect" "I18N::LangTags::List" "IO" "IO::AtomicFile"
"IO::Compress::Adapter::Bzip2" "IO::Compress::Adapter::Deflate"
"IO::Compress::Adapter::Identity" "IO::Compress::Adapter::Lzma"
"IO::Compress::Adapter::Xz" "IO::Compress::Base"
"IO::Compress::Base::Common" "IO::Compress::Bzip2" "IO::Compress::Deflate"
"IO::Compress::Gzip" "IO::Compress::Gzip::Constants" "IO::Compress::Lzma"
"IO::Compress::RawDeflate" "IO::Compress::Xz" "IO::Compress::Zip"
"IO::Compress::Zip::Constants" "IO::Compress::Zlib::Constants"
"IO::Compress::Zlib::Extra" "IO::Dir" "IO::File" "IO::Handle"
"IO::InnerFile" "IO::Interactive" "IO::Lines" "IO::Pipe" "IO::Poll"
"IO::Scalar" "IO::ScalarArray" "IO::Seekable" "IO::Select"
"IO::SessionData" "IO::SessionSet" "IO::Socket" "IO::Socket::INET"
"IO::Socket::SSL" "IO::Socket::UNIX" "IO::String" "IO::Stringy"
"IO::Uncompress::Adapter::Bunzip2" "IO::Uncompress::Adapter::Identity"
"IO::Uncompress::Adapter::Inflate" "IO::Uncompress::Adapter::UnLzma"
"IO::Uncompress::Adapter::UnXz" "IO::Uncompress::AnyInflate"
"IO::Uncompress::AnyUncompress" "IO::Uncompress::Base"
"IO::Uncompress::Bunzip2" "IO::Uncompress::Gunzip"
"IO::Uncompress::Inflate" "IO::Uncompress::RawInflate"
"IO::Uncompress::UnLzma" "IO::Uncompress::UnXz" "IO::Uncompress::Unzip"
"IO::Wrap" "IO::WrapTie" "IO::Zlib" "IPC::Cmd" "IPC::Open2" "IPC::Open3"
"IPC::Run" "IPC::Run3" "IPC::Run3::ProfArrayBuffer"
"IPC::Run3::ProfLogReader" "IPC::Run3::ProfLogger" "IPC::Run3::ProfPP"
"IPC::Run3::ProfReporter" "IPC::Run::Debug" "IPC::Run::IO"
"IPC::Run::Timer" "IPC::Run::Win32Helper" "IPC::Run::Win32IO"
"IPC::Run::Win32Pump" "IPC::System::Simple" "Imager" "Imager::API"
"Imager::APIRef" "Imager::Color" "Imager::Color::Float"
"Imager::Color::Table" "Imager::Cookbook" "Imager::CountColor"
"Imager::Draw" "Imager::Engines" "Imager::Expr" "Imager::Expr::Assem"
"Imager::ExtUtils" "Imager::File::CUR" "Imager::File::GIF"
"Imager::File::ICO" "Imager::File::JPEG" "Imager::File::PNG"
"Imager::File::SGI" "Imager::File::TIFF" "Imager::Files" "Imager::Fill"
"Imager::Filter::DynTest" "Imager::Filter::Flines"
"Imager::Filter::Mandelbrot" "Imager::Filters" "Imager::Font"
"Imager::Font::BBox" "Imager::Font::FT2" "Imager::Font::FreeType2"
"Imager::Font::Image" "Imager::Font::Truetype" "Imager::Font::Type1"
"Imager::Font::W32" "Imager::Font::Win32" "Imager::Font::Wrap"
"Imager::Fountain" "Imager::Handy" "Imager::IO" "Imager::ImageTypes"
"Imager::Inline" "Imager::LargeSamples" "Imager::Matrix2d"
"Imager::Preprocess" "Imager::Probe" "Imager::Regops" "Imager::Test"
"Imager::Transform" "Imager::Transformations" "Imager::Tutorial"
"Imager::interface" "Imager::regmach" "JSON" "JSON::PP" "JSON::PP::Boolean"
"JSON::PP::Compat5006" "JSON::XS" "JSON::XS::Boolean" "JSON::backportPP"
"JSON::backportPP::Boolean" "JSON::backportPP::Compat5005"
"JSON::backportPP::Compat5006" "LWP" "LWP::Authen::Basic"
"LWP::Authen::Digest" "LWP::Authen::Ntlm" "LWP::ConnCache" "LWP::Debug"
"LWP::DebugFile" "LWP::MediaTypes" "LWP::MemberMixin" "LWP::Online"
"LWP::Protocol" "LWP::Protocol::GHTTP" "LWP::Protocol::cpan"
"LWP::Protocol::data" "LWP::Protocol::file" "LWP::Protocol::ftp"
"LWP::Protocol::gopher" "LWP::Protocol::http" "LWP::Protocol::https"
"LWP::Protocol::loopback" "LWP::Protocol::mailto" "LWP::Protocol::nntp"
"LWP::Protocol::nogo" "LWP::RobotUA" "LWP::Simple" "LWP::UserAgent"
"List::Util" "List::Util::PP" "List::Util::XS" "Locale::Codes"
"Locale::Codes::API" "Locale::Codes::Changes" "Locale::Codes::Constants"
"Locale::Codes::Country" "Locale::Codes::Country_Codes"
"Locale::Codes::Currency" "Locale::Codes::Currency_Codes"
"Locale::Codes::LangExt" "Locale::Codes::LangExt_Codes"
"Locale::Codes::LangVar" "Locale::Codes::LangVar_Codes"
"Locale::Codes::Language" "Locale::Codes::Language_Codes"
"Locale::Codes::Script" "Locale::Codes::Script_Codes" "Locale::Constants"
"Locale::Country" "Locale::Currency" "Locale::Language" "Locale::Maketext"
"Locale::Maketext::Cookbook" "Locale::Maketext::Guts"
"Locale::Maketext::GutsLoader" "Locale::Maketext::Simple"
"Locale::Maketext::TPJ13" "Locale::Script" "Log::Message"
"Log::Message::Config" "Log::Message::Handlers" "Log::Message::Item"
"Log::Message::Simple" "MIME::Base64" "MIME::QuotedPrint" "Math::BigFloat"
"Math::BigFloat::Trace" "Math::BigInt" "Math::BigInt::Calc"
"Math::BigInt::CalcEmu" "Math::BigInt::FastCalc" "Math::BigInt::GMP"
"Math::BigInt::Trace" "Math::BigRat" "Math::Complex" "Math::GMP"
"Math::MPC" "Math::MPFR" "Math::Pari" "Math::PariInit" "Math::Trig"
"Math::libPARI" "Math::libPARI.dumb" "Memoize" "Memoize::AnyDBM_File"
"Memoize::Expire" "Memoize::ExpireFile" "Memoize::ExpireTest"
"Memoize::NDBM_File" "Memoize::SDBM_File" "Memoize::Storable"
"Module::Build" "Module::Build::API" "Module::Build::Authoring"
"Module::Build::Base" "Module::Build::Bundling" "Module::Build::Compat"
"Module::Build::Config" "Module::Build::ConfigData"
"Module::Build::Cookbook" "Module::Build::Dumper"
"Module::Build::ModuleInfo" "Module::Build::Notes"
"Module::Build::PPMMaker" "Module::Build::Platform::Amiga"
"Module::Build::Platform::Default" "Module::Build::Platform::EBCDIC"
"Module::Build::Platform::MPEiX" "Module::Build::Platform::MacOS"
"Module::Build::Platform::RiscOS" "Module::Build::Platform::Unix"
"Module::Build::Platform::VMS" "Module::Build::Platform::VOS"
"Module::Build::Platform::Windows" "Module::Build::Platform::aix"
"Module::Build::Platform::cygwin" "Module::Build::Platform::darwin"
"Module::Build::Platform::os2" "Module::Build::PodParser"
"Module::Build::Version" "Module::Build::YAML" "Module::CoreList"
"Module::Load" "Module::Load::Conditional" "Module::Loaded"
"Module::Metadata" "Module::P5Z" "Module::Plan::Archive"
"Module::Plan::Base" "Module::Plan::Lite" "Module::Pluggable"
"Module::Pluggable::Object" "Module::Signature" "Mozilla::CA" "NDBM_File"
"NEXT" "Net::Cmd" "Net::Config" "Net::Domain" "Net::FTP" "Net::FTP::A"
"Net::FTP::E" "Net::FTP::I" "Net::FTP::L" "Net::FTP::dataconn" "Net::HTTP"
"Net::HTTP::Methods" "Net::HTTP::NB" "Net::HTTPS" "Net::NNTP" "Net::Netrc"
"Net::POP3" "Net::Ping" "Net::SMTP" "Net::SMTP::TLS" "Net::SSH2"
"Net::SSH2::Channel" "Net::SSH2::Dir" "Net::SSH2::File"
"Net::SSH2::Listener" "Net::SSH2::PublicKey" "Net::SSH2::SFTP" "Net::SSL"
"Net::SSLeay" "Net::SSLeay::Handle" "Net::Time" "Net::hostent"
"Net::libnetFAQ" "Net::netent" "Net::protoent" "Net::servent"
"Number::Compare" "O" "ODBM_File" "OLE" "Object::Accessor" "Opcode" "PAR"
"PAR::Dist" "PAR::Dist::FromPPD" "PAR::Dist::InstallPPD" "PAR::Environment"
"PAR::FAQ" "PAR::Heavy" "PAR::Repository::Client"
"PAR::Repository::Client::DBM" "PAR::Repository::Client::HTTP"
"PAR::Repository::Client::Local" "PAR::Repository::Client::Util"
"PAR::Repository::Query" "PAR::SetupProgname" "PAR::SetupTemp"
"PAR::Tutorial" "POD2::DE::local::lib" "POD2::PT_BR::local::lib" "POSIX"
"Package::Constants" "Params::Check" "Params::Util" "Parse::Binary"
"Parse::Binary::FixedFormat" "Parse::Binary::FixedFormat::Variants"
"Parse::CPAN::Meta" "Perl::OSType" "PerlIO" "PerlIO::encoding"
"PerlIO::scalar" "PerlIO::via" "PerlIO::via::QuotedPrint" "Pod::Checker"
"Pod::Escapes" "Pod::Find" "Pod::Functions" "Pod::Html" "Pod::InputObjects"
"Pod::LaTeX" "Pod::Man" "Pod::ParseLink" "Pod::ParseUtils" "Pod::Parser"
"Pod::Perldoc" "Pod::Perldoc::BaseTo" "Pod::Perldoc::GetOptsOO"
"Pod::Perldoc::ToChecker" "Pod::Perldoc::ToMan" "Pod::Perldoc::ToNroff"
"Pod::Perldoc::ToPod" "Pod::Perldoc::ToRtf" "Pod::Perldoc::ToText"
"Pod::Perldoc::ToTk" "Pod::Perldoc::ToXml" "Pod::PlainText" "Pod::Select"
"Pod::Simple" "Pod::Simple::BlackBox" "Pod::Simple::Checker"
"Pod::Simple::Debug" "Pod::Simple::DumpAsText" "Pod::Simple::DumpAsXML"
"Pod::Simple::HTML" "Pod::Simple::HTMLBatch" "Pod::Simple::HTMLLegacy"
"Pod::Simple::LinkSection" "Pod::Simple::Methody" "Pod::Simple::Progress"
"Pod::Simple::PullParser" "Pod::Simple::PullParserEndToken"
"Pod::Simple::PullParserStartToken" "Pod::Simple::PullParserTextToken"
"Pod::Simple::PullParserToken" "Pod::Simple::RTF" "Pod::Simple::Search"
"Pod::Simple::SimpleTree" "Pod::Simple::Subclassing" "Pod::Simple::Text"
"Pod::Simple::TextContent" "Pod::Simple::TiedOutFH"
"Pod::Simple::Transcode" "Pod::Simple::TranscodeDumb"
"Pod::Simple::TranscodeSmart" "Pod::Simple::XHTML"
"Pod::Simple::XMLOutStream" "Pod::Text" "Pod::Text::Color"
"Pod::Text::Overstrike" "Pod::Text::Termcap" "Pod::Usage" "Probe::Perl"
"SDBM_File" "SOAP::Client" "SOAP::Constants" "SOAP::Data"
"SOAP::Deserializer" "SOAP::Fault" "SOAP::Header" "SOAP::Lite"
"SOAP::Lite::Deserializer::XMLSchema1999"
"SOAP::Lite::Deserializer::XMLSchema2001"
"SOAP::Lite::Deserializer::XMLSchemaSOAP1_1"
"SOAP::Lite::Deserializer::XMLSchemaSOAP1_2" "SOAP::Lite::Packager"
"SOAP::Lite::Utils" "SOAP::Packager" "SOAP::SOM" "SOAP::Schema"
"SOAP::Serializer" "SOAP::Server" "SOAP::Test" "SOAP::Trace"
"SOAP::Transport" "SOAP::Transport::HTTP" "SOAP::Transport::IO"
"SOAP::Transport::LOCAL" "SOAP::Transport::LOOPBACK"
"SOAP::Transport::MAILTO" "SOAP::Transport::POP3" "SOAP::Utils" "Safe"
"Scalar::Util" "Scalar::Util::PP" "Search::Dict" "SelectSaver" "SelfLoader"
"Shell" "Socket" "Sort::Versions" "Storable" "String::CRC32" "Sub::Uplevel"
"Symbol" "Sys::Hostname" "TAP::Base" "TAP::Formatter::Base"
"TAP::Formatter::Color" "TAP::Formatter::Console"
"TAP::Formatter::Console::ParallelSession"
"TAP::Formatter::Console::Session" "TAP::Formatter::File"
"TAP::Formatter::File::Session" "TAP::Formatter::Session" "TAP::Harness"
"TAP::Harness::Beyond" "TAP::Object" "TAP::Parser"
"TAP::Parser::Aggregator" "TAP::Parser::Grammar" "TAP::Parser::Iterator"
"TAP::Parser::Iterator::Array" "TAP::Parser::Iterator::Process"
"TAP::Parser::Iterator::Stream" "TAP::Parser::IteratorFactory"
"TAP::Parser::Multiplexer" "TAP::Parser::Result"
"TAP::Parser::Result::Bailout" "TAP::Parser::Result::Comment"
"TAP::Parser::Result::Plan" "TAP::Parser::Result::Pragma"
"TAP::Parser::Result::Test" "TAP::Parser::Result::Unknown"
"TAP::Parser::Result::Version" "TAP::Parser::Result::YAML"
"TAP::Parser::ResultFactory" "TAP::Parser::Scheduler"
"TAP::Parser::Scheduler::Job" "TAP::Parser::Scheduler::Spinner"
"TAP::Parser::Source" "TAP::Parser::SourceHandler"
"TAP::Parser::SourceHandler::Executable" "TAP::Parser::SourceHandler::File"
"TAP::Parser::SourceHandler::Handle" "TAP::Parser::SourceHandler::Perl"
"TAP::Parser::SourceHandler::RawTAP" "TAP::Parser::Utils"
"TAP::Parser::YAMLish::Reader" "TAP::Parser::YAMLish::Writer"
"Task::Weaken" "Term::ANSIColor" "Term::Cap" "Term::Complete"
"Term::ReadKey" "Term::ReadLine" "Term::ReadLine::Perl"
"Term::ReadLine::readline" "Term::UI" "Term::UI::History" "Test"
"Test::Builder" "Test::Builder::Module" "Test::Builder::Tester"
"Test::Builder::Tester::Color" "Test::Deep" "Test::Deep::All"
"Test::Deep::Any" "Test::Deep::Array" "Test::Deep::ArrayEach"
"Test::Deep::ArrayElementsOnly" "Test::Deep::ArrayLength"
"Test::Deep::ArrayLengthOnly" "Test::Deep::Blessed" "Test::Deep::Boolean"
"Test::Deep::Cache" "Test::Deep::Cache::Simple" "Test::Deep::Class"
"Test::Deep::Cmp" "Test::Deep::Code" "Test::Deep::Hash"
"Test::Deep::HashEach" "Test::Deep::HashElements" "Test::Deep::HashKeys"
"Test::Deep::HashKeysOnly" "Test::Deep::Ignore" "Test::Deep::Isa"
"Test::Deep::ListMethods" "Test::Deep::MM" "Test::Deep::Methods"
"Test::Deep::NoTest" "Test::Deep::Number" "Test::Deep::Ref"
"Test::Deep::RefType" "Test::Deep::Regexp" "Test::Deep::RegexpMatches"
"Test::Deep::RegexpOnly" "Test::Deep::RegexpRef"
"Test::Deep::RegexpRefOnly" "Test::Deep::RegexpVersion"
"Test::Deep::ScalarRef" "Test::Deep::ScalarRefOnly" "Test::Deep::Set"
"Test::Deep::Shallow" "Test::Deep::Stack" "Test::Deep::String"
"Test::Exception" "Test::Harness" "Test::Manifest" "Test::More"
"Test::NoWarnings" "Test::NoWarnings::Warning" "Test::Script"
"Test::Simple" "Test::Tester" "Test::Tester::Capture"
"Test::Tester::CaptureRunner" "Test::Tester::Delegate" "Test::Tutorial"
"Test::Warn" "Test::YAML" "Text::Abbrev" "Text::Balanced" "Text::Diff"
"Text::Diff::Config" "Text::Diff::Table" "Text::Glob" "Text::ParseWords"
"Text::Soundex" "Text::Tabs" "Text::Wrap" "Thread" "Thread::Queue"
"Thread::Semaphore" "Tie::Array" "Tie::EncryptedHash" "Tie::File"
"Tie::Handle" "Tie::Hash" "Tie::Hash::NamedCapture" "Tie::Memoize"
"Tie::RefHash" "Tie::Registry" "Tie::Scalar" "Tie::StdHandle"
"Tie::SubstrHash" "Time::HiRes" "Time::Local" "Time::Piece" "Time::Seconds"
"Time::gmtime" "Time::localtime" "Time::tm" "Tree::DAG_Node" "UDDI::Lite"
"UNIVERSAL" "URI" "URI::Escape" "URI::Heuristic" "URI::IRI"
"URI::QueryParam" "URI::Split" "URI::URL" "URI::WithBase" "URI::_foreign"
"URI::_generic" "URI::_idna" "URI::_ldap" "URI::_login" "URI::_punycode"
"URI::_query" "URI::_segment" "URI::_server" "URI::_userpass" "URI::data"
"URI::file" "URI::file::Base" "URI::file::FAT" "URI::file::Mac"
"URI::file::OS2" "URI::file::QNX" "URI::file::Unix" "URI::file::Win32"
"URI::ftp" "URI::gopher" "URI::http" "URI::https" "URI::ldap" "URI::ldapi"
"URI::ldaps" "URI::mailto" "URI::mms" "URI::news" "URI::nntp" "URI::pop"
"URI::rlogin" "URI::rsync" "URI::rtsp" "URI::rtspu" "URI::sip" "URI::sips"
"URI::snews" "URI::ssh" "URI::telnet" "URI::tn3270" "URI::urn"
"URI::urn::isbn" "URI::urn::oid" "Unicode::Collate"
"Unicode::Collate::CJK::Big5" "Unicode::Collate::CJK::GB2312"
"Unicode::Collate::CJK::JISX0208" "Unicode::Collate::CJK::Korean"
"Unicode::Collate::CJK::Pinyin" "Unicode::Collate::CJK::Stroke"
"Unicode::Collate::Locale" "Unicode::Normalize" "Unicode::UCD"
"User::grent" "User::pwent" "WWW::RobotRules"
"WWW::RobotRules::AnyDBM_File" "Win32" "Win32::API" "Win32::API::Callback"
"Win32::API::Struct" "Win32::API::Test" "Win32::API::Type" "Win32::DBIODBC"
"Win32::EventLog" "Win32::Exe" "Win32::Exe::Base"
"Win32::Exe::DataDirectory" "Win32::Exe::DebugDirectory"
"Win32::Exe::DebugTable" "Win32::Exe::IconFile"
"Win32::Exe::InsertResourceSection" "Win32::Exe::Manifest"
"Win32::Exe::Manifest::Parser" "Win32::Exe::PE" "Win32::Exe::PE::Header"
"Win32::Exe::PE::Header::PE32" "Win32::Exe::PE::Header::PE32Plus"
"Win32::Exe::Resource" "Win32::Exe::Resource::GroupIcon"
"Win32::Exe::Resource::Icon" "Win32::Exe::Resource::Manifest"
"Win32::Exe::Resource::Version" "Win32::Exe::ResourceData"
"Win32::Exe::ResourceEntry" "Win32::Exe::ResourceEntry::Id"
"Win32::Exe::ResourceEntry::Name" "Win32::Exe::ResourceTable"
"Win32::Exe::Section" "Win32::Exe::Section::Code"
"Win32::Exe::Section::Data" "Win32::Exe::Section::Debug"
"Win32::Exe::Section::Exports" "Win32::Exe::Section::Imports"
"Win32::Exe::Section::Resources" "Win32::File" "Win32::File::Object"
"Win32::OLE" "Win32::OLE::Const" "Win32::OLE::Enum" "Win32::OLE::Lite"
"Win32::OLE::NEWS" "Win32::OLE::NLS" "Win32::OLE::TPJ"
"Win32::OLE::TypeInfo" "Win32::OLE::Variant" "Win32::Process"
"Win32::TieRegistry" "Win32::UTCFileTime" "Win32::WinError"
"Win32API::File" "Win32API::Registry" "Win32CORE" "XML::LibXML"
"XML::LibXML::Attr" "XML::LibXML::Boolean" "XML::LibXML::CDATASection"
"XML::LibXML::Comment" "XML::LibXML::Common" "XML::LibXML::DOM"
"XML::LibXML::Document" "XML::LibXML::DocumentFragment" "XML::LibXML::Dtd"
"XML::LibXML::Element" "XML::LibXML::ErrNo" "XML::LibXML::Error"
"XML::LibXML::InputCallback" "XML::LibXML::Literal"
"XML::LibXML::Namespace" "XML::LibXML::Node" "XML::LibXML::NodeList"
"XML::LibXML::Number" "XML::LibXML::PI" "XML::LibXML::Parser"
"XML::LibXML::Pattern" "XML::LibXML::Reader" "XML::LibXML::RegExp"
"XML::LibXML::RelaxNG" "XML::LibXML::SAX" "XML::LibXML::SAX::Builder"
"XML::LibXML::SAX::Generator" "XML::LibXML::SAX::Parser"
"XML::LibXML::Schema" "XML::LibXML::Text" "XML::LibXML::XPathContext"
"XML::LibXML::XPathExpression" "XML::LibXSLT" "XML::NamespaceSupport"
"XML::Parser" "XML::Parser::Expat" "XML::Parser::Lite"
"XML::Parser::Style::Debug" "XML::Parser::Style::Objects"
"XML::Parser::Style::Stream" "XML::Parser::Style::Subs"
"XML::Parser::Style::Tree" "XML::SAX" "XML::SAX::Base"
"XML::SAX::DocumentLocator" "XML::SAX::Exception" "XML::SAX::Intro"
"XML::SAX::ParserFactory" "XML::SAX::PurePerl"
"XML::SAX::PurePerl::DTDDecls" "XML::SAX::PurePerl::DebugHandler"
"XML::SAX::PurePerl::DocType" "XML::SAX::PurePerl::EncodingDetect"
"XML::SAX::PurePerl::Exception" "XML::SAX::PurePerl::NoUnicodeExt"
"XML::SAX::PurePerl::Productions" "XML::SAX::PurePerl::Reader"
"XML::SAX::PurePerl::Reader::NoUnicodeExt"
"XML::SAX::PurePerl::Reader::Stream" "XML::SAX::PurePerl::Reader::String"
"XML::SAX::PurePerl::Reader::URI" "XML::SAX::PurePerl::Reader::UnicodeExt"
"XML::SAX::PurePerl::UnicodeExt" "XML::SAX::PurePerl::XMLDecl"
"XML::Simple" "XML::Simple::FAQ" "XMLRPC::Lite" "XMLRPC::Test"
"XMLRPC::Transport::HTTP" "XMLRPC::Transport::POP3"
"XMLRPC::Transport::TCP" "XSLoader" "YAML" "YAML::Any" "YAML::Dumper"
"YAML::Dumper::Base" "YAML::Error" "YAML::Loader" "YAML::Loader::Base"
"YAML::Marshall" "YAML::Mo" "YAML::Node" "YAML::Tag" "YAML::Tiny"
"YAML::Types" "attributes" "autodie" "autodie::exception"
"autodie::exception::system" "autodie::hints" "autouse" "base" "bigint"
"bignum" "bigrat" "blib" "bytes" "charnames" "common::sense" "constant"
"deprecate" "diagnostics" "encoding" "encoding::warnings" "feature"
"fields" "filetest" "if" "inc::latest" "inc::latest::private" "integer"
"less" "lib" "lib::core::only" "local::lib" "locale" "lwpcook" "lwptut"
"mro" "open.pod" "ops" "overload" "overload::numbers" "overloading"
"parent" "perlfilter" "perllocal" "pip" "pler" "pods::a2p" "pods::perl"
"pods::perl5004delta" "pods::perl5005delta" "pods::perl5100delta"
"pods::perl5101delta" "pods::perl5110delta" "pods::perl5111delta"
"pods::perl5112delta" "pods::perl5113delta" "pods::perl5114delta"
"pods::perl5115delta" "pods::perl5120delta" "pods::perl5121delta"
"pods::perl5122delta" "pods::perl5123delta" "pods::perl5130delta"
"pods::perl51310delta" "pods::perl51311delta" "pods::perl5131delta"
"pods::perl5132delta" "pods::perl5133delta" "pods::perl5134delta"
"pods::perl5135delta" "pods::perl5136delta" "pods::perl5137delta"
"pods::perl5138delta" "pods::perl5139delta" "pods::perl5140delta"
"pods::perl5141delta" "pods::perl5142delta" "pods::perl561delta"
"pods::perl56delta" "pods::perl570delta" "pods::perl571delta"
"pods::perl572delta" "pods::perl573delta" "pods::perl581delta"
"pods::perl582delta" "pods::perl583delta" "pods::perl584delta"
"pods::perl585delta" "pods::perl586delta" "pods::perl587delta"
"pods::perl588delta" "pods::perl589delta" "pods::perl58delta"
"pods::perl590delta" "pods::perl591delta" "pods::perl592delta"
"pods::perl593delta" "pods::perl594delta" "pods::perl595delta"
"pods::perlaix" "pods::perlamiga" "pods::perlapi" "pods::perlapio"
"pods::perlartistic" "pods::perlbeos" "pods::perlbook" "pods::perlboot"
"pods::perlbot" "pods::perlbs2000" "pods::perlcall" "pods::perlce"
"pods::perlcheat" "pods::perlclib" "pods::perlcn" "pods::perlcommunity"
"pods::perlcompile" "pods::perlcygwin" "pods::perldata"
"pods::perldbmfilter" "pods::perldebguts" "pods::perldebtut"
"pods::perldebug" "pods::perldelta" "pods::perldgux" "pods::perldiag"
"pods::perldoc" "pods::perldos" "pods::perldsc" "pods::perlebcdic"
"pods::perlembed" "pods::perlepoc" "pods::perlfaq" "pods::perlfaq1"
"pods::perlfaq2" "pods::perlfaq3" "pods::perlfaq4" "pods::perlfaq5"
"pods::perlfaq6" "pods::perlfaq7" "pods::perlfaq8" "pods::perlfaq9"
"pods::perlfilter" "pods::perlfork" "pods::perlform" "pods::perlfreebsd"
"pods::perlfunc" "pods::perlgit" "pods::perlglossary" "pods::perlgpl"
"pods::perlguts" "pods::perlhack" "pods::perlhacktips" "pods::perlhacktut"
"pods::perlhaiku" "pods::perlhist" "pods::perlhpux" "pods::perlhurd"
"pods::perlintern" "pods::perlinterp" "pods::perlintro" "pods::perliol"
"pods::perlipc" "pods::perlirix" "pods::perljp" "pods::perlko"
"pods::perllexwarn" "pods::perllinux" "pods::perllocale" "pods::perllol"
"pods::perlmacos" "pods::perlmacosx" "pods::perlmod" "pods::perlmodinstall"
"pods::perlmodlib" "pods::perlmodstyle" "pods::perlmpeix"
"pods::perlmroapi" "pods::perlnetware" "pods::perlnewmod"
"pods::perlnumber" "pods::perlobj" "pods::perlop" "pods::perlopenbsd"
"pods::perlopentut" "pods::perlos2" "pods::perlos390" "pods::perlos400"
"pods::perlpacktut" "pods::perlperf" "pods::perlplan9" "pods::perlpod"
"pods::perlpodspec" "pods::perlpodstyle" "pods::perlpolicy"
"pods::perlport" "pods::perlpragma" "pods::perlqnx" "pods::perlre"
"pods::perlreapi" "pods::perlrebackslash" "pods::perlrecharclass"
"pods::perlref" "pods::perlreftut" "pods::perlreguts" "pods::perlrequick"
"pods::perlreref" "pods::perlretut" "pods::perlriscos" "pods::perlrun"
"pods::perlsec" "pods::perlsolaris" "pods::perlsource" "pods::perlstyle"
"pods::perlsub" "pods::perlsymbian" "pods::perlsyn" "pods::perlthrtut"
"pods::perltie" "pods::perltoc" "pods::perltodo" "pods::perltooc"
"pods::perltoot" "pods::perltrap" "pods::perltru64" "pods::perltw"
"pods::perlunicode" "pods::perlunifaq" "pods::perluniintro"
"pods::perluniprops" "pods::perlunitut" "pods::perlutil" "pods::perluts"
"pods::perlvar" "pods::perlvmesa" "pods::perlvms" "pods::perlvos"
"pods::perlwin32" "pods::perlxs" "pods::perlxstut" "re" "sigtrap"
"sort.pod" "strict" "subs" "threads" "threads::shared" "utf8" "vars"
"version" "version::Internals" "version::Requirements" "version::vxs"
"vmsish" "warnings" "warnings::register"))
