(require-package 'sr-speedbar)

(require 'sr-speedbar)
(global-set-key [f8] 'sr-speedbar-toggle)
(setq speedbar-mode-hook '(lambda () 
    ;;(make-face 'speedbar-face)
    ;;(set-face-font 'speedbar-face "Monaco-10")
    ;;(buffer-face-set 'speedbar-face)
    (setq linum-mode nil)
    (setq sr-speedbar-right-side t)
    (setq pop-up-windows nil)
    ;;(setq sr-speedbar-width 35)
    (setq speedbar-show-unknown-files t)
    (setq speedbar-use-images nil)
    (setq sr-speedbar-auto-refresh t)
    )
)

(provide 'init-sr-speedbar)